version: "3.7"

services:
  backend:
    image: docker.pkg.github.com/tuuturu/dialogia-backend/dialogia-backend:0.0.3
    build: .
    ports:
      - '3000:3000'
      - '8081:8081'
    networks:
      - dialogia

  frontend:
    image: docker.pkg.github.com/tuuturu/dialogia-frontend/dialogia-frontend:0.1.5
    ports:
      - '80:80'
    networks:
      - dialogia

networks:
  dialogia:
