{{- if not .Values.app.apiKeyRef }}
apiVersion: v1
data:
    api-key: {{ .Values.app.apiKey | b64enc }}
kind: Secret
metadata:
    name: {{ template "feedback.fullname" . }}-email-api-key
type: Opaque
        {{- end }}