# Default values for feedback.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  env:
    - name: DISCOVERY_URL
      value: https://login-test.oslo.kommune.no/auth/realms/api-catalog/.well-known/openid-configuration
  #  - name: EMAIL_API_ENDPOINT_URL
  #    value: https://email-test.api-test.oslo.kommune.no/email

ingress:
  host: devportal-feedback.k8s-test.oslo.kommune.no
